lib/era_web/router.ex
defmodule EraWeb.Router do
  use EraWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {EraWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin do
    plug EraWeb.EnsureRolePlug, :admin
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", EraWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/user", EraWeb do
    pipe_through :browser

    get "/profile", UserController, :index
    put "/profile/transfer/:id", UserController, :transfer
    post "/profile/transfer/:id", UserController, :transfer
    get "/profile/transfer/:id", UserController, :edit
    post "/profile/buy/reward/:id", UserController, :buy_reward
    put "/profile/buy/reward/:id", UserController, :buy_reward
  end

  scope "/admin", EraWeb do
    pipe_through [:browser, :admin]

    get "/panel", AdminController, :index
    get "/rewards", AdminController, :new
    get "/reports", AdminController, :reports
    post "/rewards/new", AdminController, :create
    get "/rewards/:id/edit", AdminController, :edit
    put "/rewards/:id", AdminController, :update
    delete "/rewards/:id", AdminController, :delete
    get "/user/:id/edit", AdminController, :edit_user_points
    put "/user/:id", AdminController, :update_user_points

  end

  # Other scopes may use custom stacks.
  # scope "/api", EraWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: EraWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/era_web/views/layout_view.ex
defmodule EraWeb.LayoutView do
  use EraWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/era_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/era_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/era_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Era", suffix: " · Employee Reward App" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <nav class="orange darken-4">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          ERA
        </a>

        <ul class="right" style="font-size: 1rem;">
          <%= if Pow.Plug.current_user(@conn) do %>
            <li>
              <%= link "User Profile", to: Routes.user_path(@conn, :index)%>
            </li>

            <%= if Era.Users.is_admin?(@current_user) do %>
              <li>
                <%= link "Admin Panel", to: Routes.admin_path(@conn, :index)%>
              </li>

              <li>
                <%= link "Reports", to: Routes.admin_path(@conn, :reports)%>
              </li>
            <% end %>

            <li>
              <%= link "Edit Profile", to: Routes.pow_registration_path(@conn, :edit) %>
            </li>

            <li>
              <%= link "Sign Out", to: Routes.pow_session_path(@conn, :delete), method: :delete %>
            </li>

            <li style="border-left: 2px solid white; height: 100%; padding: 0px 15px">
              Signed in as:
              <%= @current_user.email %>
            </li>

            <li style="border-left: 2px solid rgba(255,255,255,0.4); height: 100%; padding: 0px 15px;">
              Total points:
              <%= @current_user.number_of_points %>
            </li>
          <% else %>
            <li>
                <%= link "Register", to: Routes.pow_registration_path(@conn, :new) %>
            </li>
            <li>
              <%= link "Sign In", to: Routes.pow_session_path(@conn, :new) %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= @inner_content %>
  </body>
</html>